# Generated by Django 5.2.4 on 2025-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='esperando', max_length=20)),
            ],
        ),
    ]
