# Generated by Django 5.2.4 on 2025-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blanco', '0002_gamesession_host_gameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='palabra_secreta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
