# Generated by Django 5.2.4 on 2025-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blanco', '0003_gameplayer_palabra_secreta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraPar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_buena', models.CharField(max_length=100)),
                ('palabra_infiltrado', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
