# Generated by Django 5.2.4 on 2025-07-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blanco', '0004_palabrapar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='es_impostor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='palabra_impostor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ronda_terminada',
            field=models.BooleanField(default=False),
        ),
    ]
