# Generated by Django 5.2.4 on 2025-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blanco', '0005_gameplayer_eliminado_gameplayer_es_impostor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='es_bueno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='es_infiltrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='ronda_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='palabra_buena_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='palabra_infiltrado_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ronda_actual',
            field=models.IntegerField(default=1),
        ),
    ]
