# Generated by Django 5.2.4 on 2025-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blanco', '0006_gameplayer_es_bueno_gameplayer_es_infiltrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='ya_intento_adivinar',
            field=models.BooleanField(default=False, help_text='Si el impostor ya intentó adivinar en esta ronda'),
        ),
    ]
