# Generated by Django 5.2.4 on 2025-07-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blanco', '0007_gameplayer_ya_intento_adivinar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='ya_intento_adivinar',
            field=models.BooleanField(default=False),
        ),
    ]
