from django.core.management.base import BaseCommand
from blanco.models import PalabraPar

class Command(BaseCommand):
    help = 'Pobla la base de datos con pares de palabras para el juego Blanco'

    def handle(self, *args, **options):
        # AQUÍ PON TU LISTA DE PALABRAS
        palabras = [
            ("Gato", "Perro"),
            ("Lobo", "Perro"),
            ("Blanco", "Negro"),
            ("Sol", "Luna"),
            ("Agua", "Fuego"),
            ("Día", "Noche"),
            ("Cielo", "Tierra"),
            ("Playa", "Montaña"),
            ("Verano", "Invierno"),
            ("Primavera", "Otoño"),
            ("Libro", "Película"),
            ("Música", "Silencio"),
            ("Coche", "Camión"),
            ("Café", "Té"),
            ("Cebra", "Tigre"),
            ("Caballo", "Cebra"),
            ("Adidas", "Nike"),
            ("Avión", "Nave"),
            ("Senderismo", "Footing"),
            ("Sol", "Calor"),
            ("Pizza", "Hamburguesa"),
            ("Profesor", "Alumno"),
            ("Mar", "Playa"),
            ("Fútbol", "Baloncesto"),
            ("Baloncesto", "Balonmano"),
            ("PlayStation", "Xbox"),
            ("Playa", "Piscina"),
            ("Montaña", "Colina"),
            ("Cerveza", "Vino"),
            ("Instagram", "TikTok"),
            ("FIFA", "PES - Videojuego fútbol"),
            ("Netflix", "HBO"),
            ("Marvel", "DC"),
            ("Spotify", "YouTube"),
            ("Vídeo", "Foto"),
            ("Móvil", "Ordenador"),
            ("MacDonald", "Burguer King"),
            ("Harry Potter", "Voldemort"),
            ("Batman", "Robin"),
            ("Ibiza", "Mallorca"),
            ("Croquetas", "Tortilla española"),
            ("Zapatillas", "Chanclas"),
            ("Fiesta", "Resaca"),
            ("Librería", "Biblioteca"),
            ("Instituto", "Universidad"),
            ("Colegio", "Guardería"),
            ("Sábado", "Domingo"),
            ("Zara", "H&M"),
            ("Amazon", "AliExpress"),
            ("Whatsapp", "Telegram"),
            ("Croissant", "Donut"),
            ("Gimnasio", "Gimnasia"),
            ("Tenis", "Pádel"),
            ("Madrid", "Barcelona"),
            ("Dormir", "Soñar"),
            ("Tapas", "Cañas"),
            ("Kebab", "Durum"),
            ("Apple", "Samsung"),
            ("Coche", "Moto"),
            ("TikTok", "Reels"),
            ("Cerveza", "Tinto"),
            ("DJ", "Discoteca"),
            ("Festival", "Concierto"),
            ("Apple Music", "Spotify"),
            ("Netflix", "Palomitas"),
            ("Twitch", "Stream"),
            ("Airbnb", "Booking"),
            ("Lebron", "Jordan"),
            ("Skate", "Patinete"),
            ("Vacaciones", "Maleta"),
            ("Jeans", "Sudadera"),
            ("Meme", "Sticker"),
            ("Sábado", "Copas"),
            ("Fútbol", "Champions"),
            ("Basket", "NBA"),
            ("Freestyle", "Batalla"),
            ("Trap", "Reggaetón"),
            ("Previa", "After"),
            ("Concierto", "Entrada"),
            ("Camisa", "Traje"),
            ("Serie", "Maratón"),
            ("Tinder", "Match"),
            ("Like", "Comentario"),
            ("Hashtag", "Etiqueta"),
            ("Link", "Bio"),
            ("Emoji", "GIF"),
            ("Stories", "Highlights"),
            ("Gaming", "Setup"),
            ("Podcast", "Micrófono"),
            ("Gafas", "Lupa"),
            ("Cine", "Butaca"),
            ("Tarta", "Velas"),
            ("Cumpleaños", "Regalo"),
            ("Foto", "Selfie"),
            ("Camino", "Meta"),
            ("Lunes", "Miércoles"),
            ("Trabajo", "Dinero"),
            ("Ciclismo", "Running"),
            ("Bici", "Casco"),
            ("Champú", "Ducha"),
            ("Perfume", "Colonia"),
            ("Snapchat", "Filtros"),
            ("LOL", "Valorant"),
            ("Switch", "Mario"),
            ("Halloween", "Disfraz"),
            ("Navidad", "Regalos"),
            ("Uvas", "Campanadas"),
            ("Roscón", "Chocolate"),
            ("Calimocho", "Botellón"),
            ("Bebida", "Hielo"),
            ("Hielo", "Copa"),
            ("Bar", "Terraza"),
            ("Ropa", "Armario"),
            ("Camiseta", "Shorts"),
            ("Guacamole", "Nachos"),
            ("Salsa", "Picante"),
            ("Chiringuito", "Sombra"),
            ("Mar", "Olas"),
            ("Ola", "Surf"),
            ("Sol", "Protector"),
            ("Piedras", "Arena"),
            ("Toalla", "Sombrilla"),
            ("Tarrina", "Cucurucho"),
            ("Crema", "Bronceador"),
            ("Sandía", "Melón"),
            ("Dominos", "Telepizza"),
            ("Cloro", "Sal"),
            ("Oxígeno", "Helio"),
            ("Drone", "Cámara"),
            ("Foto", "Filtro"),
            ("Sombra", "Sombrero"),
            ("Amor", "Pareja"),
            ("Odio", "Amor"),
            ("Pareja", "Cita"),
            ("San Valentín", "Rosas"),
            ("Desayuno", "Tostadas"),
            ("Brunch", "Huevos"),
            ("Música", "Bailar"),
            ("Baile", "Coreografía"),
            ("TikTok", "Baile"),
            ("iPhone", "AirPods"),
            ("AirPods", "Música"),
            ("Android", "Apple"),
            ("DJ", "Remix"),
            ("Concierto", "Altavoces"),
            ("Gorra", "Sombrero"),
            ("Silla", "Mesa"),
            ("Café", "Mañana"),
            ("Cerveza", "Noche"),
            ("Fiesta", "Amigos"),
            ("Viaje", "Mochila"),
            ("Excursión", "Ruta"),
            ("Ruta", "Mapa"),
            ("Tesoro", "Mapa"),
            ("Google", "Maps"),
            ("Meme", "Risa"),
            ("Like", "Corazón"),
            ("Estrella", "Favorito"),
            ("Barbacoa", "Chorizo"),
            ("Bocata", "Jamón"),
            ("Postre", "Dulce"),
            ("Tarta", "Chocolate"),
            ("Chocolate", "Nocilla"),
            ("Nocilla", "Pan"),
            ("Desayuno", "Café"),
            ("Noche", "Fiesta"),
            ("Coche", "Viaje"),
            ("Tren", "Billete"),
            ("Avión", "Aterrizaje"),
            ("Pasaporte", "DNI"),
            ("Maleta", "Mochila"),
            ("Aeropuerto", "Estación"),
            ("Vacaciones", "Viaje"),
            ("Euro", "Dólar"),
            ("Cripto", "Bitcoin"),
            ("Inversión", "Ahorro"),
            ("CV", "Entrevista"),
            ("Clase", "Profesor"),
            ("Deberes", "Examen"),
            ("Biblioteca", "Silencio"),
            ("Copa", "Brindis"),
            ("Copa", "Cristal"),
            ("Amigo", "Confianza"),
            ("Consola", "Mando"),
            ("Juego", "Pantalla"),
            ("Teclado", "Ratón"),
            ("Tatuaje", "Tinta"),
            ("Piercing", "Aro"),
            ("Uñas", "Esmalte"),
            ("Cabello", "Tinte"),
            ("Look", "Estilo"),
            ("Moda", "Tendencia"),
            ("Desfile", "Pasarela"),
            ("Marca", "Logo"),
            ("YouTube", "Canal"),
            ("Canal", "Suscripción"),
            ("Vídeo", "Edición"),
            ("Stream", "Chat"),
            ("Chat", "Mensaje"),
            ("Mensaje", "Notificación"),
            ("Notificación", "Icono"),
            ("Pantalla", "Brillo"),
            ("Cámara", "Objetivo"),
            ("Reels", "Historias"),
            ("Pulgar", "Meñique"),
            ("Expresión", "Gesto"),
            ("Clave", "Usuario"),
            ("Contraseña", "Seguridad"),
            ("Seguridad", "Privacidad"),
            ("Cielo", "Nube"),
            ("Trabajo", "Currículum"),
            ("Sueldo", "Contrato"),
            ("Contrato", "Firma"),
            ("Firma", "Bolígrafo"),
            ("Bolígrafo", "Lápiz"),
            ("Cuaderno", "Agenda"),
            ("Agenda", "Calendario"),
            ("Calendario", "Fecha"),
            ("Fecha", "Evento"),
            ("Evento", "Entrada"),
            ("Entrada", "Festival"),
            ("Festival", "Música"),
            ("Música", "Auriculares"),
            ("Auriculares", "Bluetooth"),
            ("Bluetooth", "Conexión"),
            ("Conexión", "WiFi"),
            ("WiFi", "Internet"),
            ("Clave", "Contraseña"),
            ("Internet", "Redes"),
            ("Redes", "Social"),
            ("Tendencia", "Hashtag"),
            ("Hashtag", "Challenge"),
            ("Challenge", "Baile"),
            ("Baile", "Escenario"),
            ("Escenario", "Luces"),
            ("Luces", "Cámara"),
            ("Cámara", "Acción"),
            ("Acción", "Película"),
            ("Película", "Palomitas"),
            ("Palomitas", "Refresco"),
            ("Refresco", "Vaso"),
            ("Vaso", "Hielo"),
            ("Cubo", "Cuadrado"),
            ("Tapa", "Bebida"),
            ("Bar", "Tapa"),
            ("Naranja", "Limón"),
            ("Ginebra", "Ron"),
            ("Ron", "Cocacola"),
            ("Cocacola", "Café"),
            ("Café", "Leche"),
            ("Leche", "Colacao"),
            ("Galletas", "Chocolate"),
            ("Chocolate", "Tableta"),
            ("Tablet", "Pantalla"),
            ("Rastro", "Huella"),
            ("Grupo", "Amigos"),
            ("Amigos", "Diversión"),
            ("Diversión", "Juego"),
            ("Juego", "Cartas"),
            ("Cartas", "Apuestas"),
            ("Apuestas", "Casino"),
            ("Casino", "Ruleta"),
            ("Ruleta", "Rojo"),
            ("Rojo", "Negro"),
            ("Negro", "Blanco"),
            ("Blanco", "Gris"),
            ("Gris", "Oscuro"),
            ("Oscuridad", "Luz"),
            ("Luz", "Ventana"),
            ("Ventana", "Cortina"),
            ("Persiana", "Ventana"),
            ("Cortina", "Habitación"),
            ("Habitación", "Cama"),
            ("Cama", "Sábanas"),
            ("Sábanas", "Almohada"),
            ("Almohada", "Sueño"),
            ("Sueño", "Despertador"),
            ("Despertador", "Temprano"),
            ("Clases", "Universidad"),
            ("Universidad", "Carrera"),
            ("Carrera", "Examen"),
            ("Examen", "Nota"),
            ("Nota", "Suspenso"),
            ("Suspenso", "Aprobado"),
            ("Curso", "Asignatura"),
            ("Asignatura", "Apuntes"),
            ("Apuntes", "Resumen"),
            ("Apuntes", "Estudio"),
            ("Motivación", "Logro"),
            ("Logro", "Meta"),
            ("Meta", "Objetivo"),
            ("Objetivo", "Éxito"),
            ("Éxito", "Celebración"),
            ("Celebración", "Brindis"),
            ("Comentario", "Reacción"),
            ("Roto", "Partido"),
            ("Drama", "Serie"),
            ("Final", "Spoiler"),
            ("Enfado", "Tristeza"),
            ("Audios", "WhatsApp"),
            ("WhatsApp", "Chat"),
            ("Móvil", "Notificaciones"),
            ("Pantalla", "Brillo"),
            ("Configuración", "Ajustes"),
            ("Ajustes", "Modo"),
            ("Claro", "Oscuro"),
            ("Oscuro", "Noche"),
            ("Noche", "Estrellas"),
            ("Estrellas", "Cielo"),
            ("Cielo", "Avión"),
            ("Avión", "Maleta"),
            ("Maleta", "Aeropuerto"),
            ("Aeropuerto", "Esperar"),
            ("Esperar", "Cola"),
            ("Cansancio", "Sueño"),
            ("Sueño", "Dormir"),
            ("Dormir", "Roncar"),
            ("Roncar", "Cerdo"),
            ("Abrazo", "Beso"),
            ("Beso", "Cita"),
            ("Ropa", "Look"),
            ("Look", "Estilo"),
            ("Estilo", "Moda"),
            ("Reels", "Instagram"),
            ("Instagram", "Foto"),
            ("Móvil", "Ordenador"),
            ("App", "Móvil"),
            ("Móvil", "Cargador"),
            ("Cargador", "Enchufe"),
            ("Enchufe", "Corriente"),
            ("Corriente", "Electricidad"),
            ("Factura", "Pago"),
            ("Transferencia", "Bizum"),
            ("Bizum", "Transferencia"),
            ("Transferencia", "Banco"),
            ("Banco", "Dinero"),
            ("Dinero", "Ahorro"),
            ("Ahorro", "Gasto"),
            ("Gasto", "Caro"),
            ("Caro", "Lujo"),
            ("Reloj", "Pulsera"),
            ("Pulsera", "Complemento"),
            ("Complemento", "Moda"),
            ("Moda", "Influencer"),
            ("Influencer", "Redes"),
            ("Redes", "Tendencia"),
            ("TikTok", "Challenge"),
            ("Hashtag", "Viral"),
            ("Viral", "Views"),
            ("Views", "Likes"),
            ("Likes", "Comentarios"),
            ("Comentarios", "Reacciones"),
            ("Reacciones", "Stickers"),
            ("Stickers", "Memes"),
            ("Generoso", "Tacaño"),
            ("Perfil", "Biografía"),
            ("Tienda", "Carrito"),
            ("Carrito", "Pedido"),
            ("Pedido", "Repartidor"),
            ("Repartidor", "Moto"),
            ("Moto", "Calle"),
            ("Calle", "Ciudad"),
            ("Ciudad", "Pueblo"),
            ("Mapa", "GPS"),
            ("Destino", "Viaje"),
            ("Fotos", "Álbum"),
            ("Álbum", "Recuerdo"),
            ("Recuerdo", "Anécdota"),
            ("Anécdota", "Risa"),
            ("Risa", "Carcajada"),
            ("Plan", "Cita"),
            ("Cita", "Cena"),
            ("Cena", "Restaurante"),
            ("Restaurante", "Mesa"),
            ("Mesa", "Silla"),
            ("Silla", "Asiento"),
            ("Concierto", "Entradas"),
            ("Esperar", "Hora"),
            ("Hora", "Reloj"),
            ("Reloj", "Alarma"),
            ("Alarma", "Despertar"),
            ("Despertar", "Mañana"),
            ("Mañana", "Desayuno"),
            ("Desayuno", "Zumo"),
            ("Zumo", "Naranja"),
            ("Naranja", "Fruta"),
            ("Fruta", "Batido"),
            ("Batido", "Proteína"),
            ("Proteína", "Gimnasio"),
            ("Gimnasio", "Rutina"),
            ("Rutina", "Entrenamiento"),
            ("Entrenamiento", "Fuerza"),
            ("Fuerza", "Músculo"),
            ("Músculo", "Hueso"),
            ("WhatsApp", "Mensaje"),
            ("Mensaje", "Audio"),
            ("Audio", "Silencio"),
            ("Modo", "Avión"),
            ("Avión", "Despegue"),
            ("Despegue", "Aterrizaje"),
            ("Carretera", "Asfalto"),
            ("Carril", "Carretera"),
            ("Cerradura", "Llaves"),
            ("Llaves", "Casa"),
            ("Casa", "Puerta"),
            ("Puerta", "Cerradura"),
            ("Llave", "Candado"),
            ("Bicicleta", "Pedales"),
            ("Velocidad", "Carrera"),
            ("Carrera", "Meta"),
            ("Meta", "Victoria"),
            ("Victoria", "Premio"),
            ("Premio", "Trofeo"),
            ("Trofeo", "Campeón"),
            ("Campeón", "Medalla"),
            ("Medalla", "Oro"),
            ("Oro", "Plata"),
            ("App", "TikTok"),
            ("Estética", "Maquillaje"),
            ("Maquillaje", "Brocha"),
            ("Base", "Cimiento"),
            ("Brocha", "Color"),
            ("Ojos", "Mirada"),
            ("Flecha", "Cupido"),
            ("Cupido", "Amor"),
            ("Cita", "Película"),
            ("Película", "Comedia"),
            ("Comedia", "Risa"),
            ("Risa", "Diversión"),
            ("Fiesta", "Fin de semana"),
            ("Amanecer", "Atardecer"),
            ("Arena", "Castillo"),
            ("Castillo", "Dragón"),
            ("Dragón", "Fuego"),
            ("Fuego", "Barbacoa"),
            ("Barbacoa", "Chorizo"),
            ("Chorizo", "Pan"),
            ("Pan", "Tomate"),
            ("Tomate", "Queso"),
            ("Queso", "Pizza"),
            ("Orégano", "Especias"),
            ("Especias", "Curry"),
            ("Arroz", "Sushi"),
            ("Sushi", "Soja"),
            ("Palillos", "Cubiertos"),
            ("Salsa", "Ketchup"),
            ("Ketchup", "Mostaza"),
            ("Mostaza", "Mayonesa"),
            ("Perrito", "Hamburguesa"),
            ("Mostaza", "Kétchup"),
            ("Mancha", "Camisa"),
            ("Camisa", "Plancha"),
            ("Plancha", "Arruga"),
            ("Calor", "Verano"),
            ("Verano", "Helado"),
            ("Helado", "Chocolate"),
            ("Chocolate", "Brownie"),
            ("Nuez", "Fruto"),
            ("Seco", "Agua"),
            ("Agua", "Botella"),
            ("Botella", "Cristal"),
            ("Cristal", "Ventana"),
            ("Sueño", "Despertador"),
            ("Despertador", "Ruido"),
            ("Ruido", "Molestia"),
            ("Vecino", "Edificio"),
            ("Edificio", "Ascensor"),
            ("Ascensor", "Botón"),
            ("Planta", "Maceta"),
            ("Maceta", "Tierra"),
            ("Tierra", "Jardín"),
            ("Tierra", "Marte"),
            ("Jardín", "Flores"),
            ("Flores", "Ramo"),
            ("Ramo", "Rosas"),
            ("Rosas", "Rojo"),
            ("Rojo", "Corazón"),
            ("Corazón", "Amor"),
            ("Amor", "Carta"),
            ("Carta", "Sobre"),
            ("Sobre", "Sello"),
            ("Sello", "Correo"),
            ("Correo", "Paquete"),
            ("Paquete", "Repartidor"),
            ("Seguridad", "Alarma"),
            ("Alarma", "Sistema"),
            ("Mando", "TV"),
            ("TV", "Serie"),
            ("Serie", "Temporada"),
            ("Domingo", "Relax"),
            ("Relax", "Peli"),
            ("Peli", "Sofá"),
            ("Sofá", "Manta"),
            ("Manta", "Frío"),
            ("Frío", "Invierno"),
            ("Invierno", "Lluvia"),
            ("Lluvia", "Paraguas"),
            ("Paraguas", "Charco"),
            ("Charco", "Bota"),
            ("Bota", "Calcetín"),
            ("Calcetín", "Pie"),
            ("Pie", "Zapato"),
            ("Zapato", "Tacón"),
            ("Tacón", "Vestido"),
            ("Vestido", "Traje"),
            ("Día", "Hora"),
            ("Hora", "Minuto"),
            ("Minuto", "Segundo"),
            ("Segundo", "Reloj"),
            ("Pulsera", "Accesorio"),
            ("Ropa", "Outfit"),
            ("Sol", "Sombrero"),
            ("Gorra", "Visera"),
            ("Campo", "Fútbol"),
            ("Fútbol", "Balón"),
            ("Balón", "Gol"),
            ("Gol", "Celebración"),
            ("Celebración", "Abrazo"),
            ("Restaurante", "Menú"),
            ("Menú", "Postre"),
            ("Postre", "Tarta"),
            ("Regalo", "Lazo"),
            ("Labial", "Gloss"),
            ("Gloss", "Brillo"),
            ("Brillo", "Ojos"),
            ("Ojos", "Pestañas"),
            ("Pestañas", "Rímel"),
            ("Toallita", "Desmaquillar"),
            ("Crema", "Cara"),
            ("Descanso", "Silencio"),
            ("Cielo", "Estrellas"),
            ("Estrellas", "Constelación"),
            ("Constelación", "Espacio"),
            ("Espacio", "NASA"),
            ("NASA", "Cohete"),
            ("Cohete", "Astronauta"),
            ("Astronauta", "Luna"),
            ("Luna", "Noche"),
            ("Nave", "Astronauta"),
            ("Asteroide", "Meteorito"),
            ("Tierra", "Júpiter"),
            ("Júpiter", "Saturno"),
            ("Estrella", "Galaxia"),
            ("Galaxia", "Universo"),
            ("Universo", "Big Bang"),
            ("Dictadura", "Política"),
            ("Política", "Economía"),
            ("Crecimiento", "Desarrollo"),
            ("Desarrollo", "Progreso"),
            ("Dictador", "Político"),
            ("Democracia", "Dictadura"),
            ("Presidente", "Dictador"),
            ("Representante", "Presidente"),
            ("Diputado", "Representante"),
            ("Alegría", "Felicidad"),
            ("Felicidad", "Contento"),
            ("Contento", "Satisfacción"),
            ("Satisfacción", "Alegria"),
            ("Tristeza", "Depresión"),
            ("Depresión", "Ansiedad"),
            ("Ansiedad", "Pánico"),
            ("Pánico", "Miedo"),
            ("Llorrar", "Lágrimas"),
            ("Lágrimas", "Llanto"),
            ("Crisis", "Desastre"),
            ("Desastre", "Catástrofe"),
            ("Inundación", "Incendio"),
            ("Incendio", "Fuego"),
            ("Calor", "Frio"),
            ("Frio", "Hielo"),
            ("Hielo", "Nieve"),
            ("Lluvia", "Tormenta"),
            ("Esquí", "Snow"),
            ("Portugal", "España"),
            ("España", "Francia"),
            ("Francia", "Alemania"),
            ("Alemania", "Italia"),
            ("Italia", "Reino Unido"),
            ("Reino Unido", "Irlanda"),
            ("Irlanda", "Escocia"),
            ("EEUU", "Canadá"),
            ("Canadá", "México"),
            ("México", "Brasil"),
            ("Brasil", "Argentina"),
            ("Argentina", "Chile"),
            ("Chile", "Perú"),
            ("Perú", "Colombia"),
            ("Madrid", "Barcelona"),
            ("Barcelona", "Valencia"),
            ("Valencia", "Sevilla"),
            ("Sevilla", "Málaga"),
            ("Málaga", "Cádiz"),
            ("Cádiz", "Córdoba"),
            ("Córdoba", "Jaén"),
            ("Jaén", "Almería"),
            ("Almería", "Granada"),
            ("Granada", "Málaga"),
            ("Asturias", "Galicia"),
            ("Galicia", "Cataluña"),
            ("Cataluña", "Valencia"),
            ("Valencia", "Murcia"),
            ("Murcia", "Andalucía"),
            ("Andalucía", "Extremadura"),
            ("Extremadura", "Castilla-La Mancha"),
            ("Castilla-La Mancha", "Castilla y León"),
            ("Cataluña", "País Vasco"),
            ("País Vasco", "Navarra"),
            ("Navarra", "Aragón"),
            ("Aragón", "Cataluña"),
            ("Mono", "Chimpancé"),
            ("Chimpancé", "Gorila"),
            ("Gorila", "Orangután"),
            ("Orangután", "Babuino"),
            ("Babuino", "Marmota"),
            ("Marmota", "Conejo"),
            ("Conejo", "Zorro"),
            ("Zorro", "Lobo"),
            ("Delfín", "Tiburón"),
            ("Tiburón", "Pez"),
            ("Corriente", "Río"),
            ("Río", "Mar"),
            ("Mar", "Oceano"),
            ("Tienda", "Mercado"),
            ("Supermercado", "Almacén"),
            ("Almacén", "Tienda"),
            ("Hitler", "Nazis"),
            ("Nazis", "Alemania"),
            ("Alemania", "Francia"),
            ("Guerra Mundial", "Hitler"),
            ("Nazis", "Judíos"),
            ("Judíos", "Holocausto"),
            ("Ladrón", "Asesino"),
            ("Asesino", "Crimen"),
            ("Crimen", "Prisión"),
            ("Prisión", "Carcel"),
            ("Cárcel", "Condena"),
            ("Condena", "Libertad"),
            ("Franco", "Dictadura"),
            ("República", "Monarquía"),
            ("Monarquía", "Dictadura"),
            ("China", "Japón"),
            ("Japón", "Corea"),
            ("Corea", "China"),
            ("Australia", "Nueva Zelanda"),
            ("Animales", "Australia"),
            ("Terremoto", "Tsunami"),
            ("Tsunami", "Ola"),
            ("Napoleón", "Alejandro Magno"),
            ("Cleopatra", "Egipto"),
            ("Leonardo da Vinci", "Miguel Ángel"),
            ("Shakespeare", "Cervantes"),
            ("Einstein", "Newton"),
            ("Mozart", "Beethoven"),
            ("Marco Polo", "Cristóbal Colón"),
            ("Cristóbal Colón", "América"),
            ("América", "Europa"),
            ("Europa", "África"),
            ("África", "Asia"),
            ("Asia", "Oceanía"),
            ("Oceanía", "Antártida"),
            ("Luke Skywalker", "Darth Vader"),
            ("Frodo", "Gollum"),
            ("Indiana Jones", "Lara Croft"),
            ("Superman", "Batman"),
            ("Spider-Man", "Iron Man"),
            ("Mickey Mouse", "Pato Donald"),
            ("Simba", "Mufasa"),
            ("Simba", "Nala"),
            ("Juego de Tronos", "Walking Dead"),
            ("Don Quijote", "Sancho Panza"),
            ("Romeo", "Julieta"),
            ("Drácula", "Frankenstein"),
            ("Peter Pan", "Capitán Garfio"),
            ("Cenicienta", "Blancanieves"),
            ("Pinocho", "Gepetto"),
            ("Zeus", "Poseidón"),
            ("Hércules", "Aquiles"),
            ("Medusa", "Sirena"),
            ("Thor", "Capitán América"),
            ("Robin Hood", "Robar"),
            ("King Kong", "Godzilla"),
            ("Superman", "Hulk"),
            ("Mario", "Luigi"),
            ("Captain America", "Iron Man"),
            ("Tom", "Jerry"),
            ("Bugs Bunny", "Pato Donald"),
            ("Goku", "Vegeta"),
            ("Elvis Presley", "Michael Jackson"),
            ("Madonna", "Lady Gaga"),
            ("The Beatles", "The Rolling Stones"),
            ("Queen", "ABBA"),
            ("Bad Bunny", "Myke Towers"),
            ("Quevedo", "Saiko"),
            ("Rauw Alejandro", "Bad Bunny"),
            ("Gandhi", "Mandela"),
            ("Einstein", "Tesla"),
            ("Steve Jobs", "Bill Gates"), 
            ("Mark Zuckerberg", "Elon Musk"),
            ("Obama", "Trump"),
            ("Pelé", "Maradona"),
            ("Boxeo", "Mike Tyson"),
            ("Música", "Rock"),
            ("Rock", "Pop"),
            ("Pop", "Jazz"),
            ("Jazz", "Clásica"),
            ("Rosalía", "Rauw Alejandro"),
            ("Shakira", "Bizarrap"),
            ("Ibai Llanos", "Gerard Piqué"),
            ("Cristiano Ronaldo", "Lionel Messi"),
            ("Rafael Nadal", "Roger Federer"),
            ("Rafael Nadal", "Carlos Alcaraz"),
            ("Rafael Nadal", "Novak Djokovic"),
            ("Hamilton", "Fernando Alonso"),
            ("Fernando Alonso", "F1"),
            ("Xokas", "Ibai Llanos"),
            ("El Rubius", "AuronPlay"),
            ("Emilia", "Duki"),
            ("Neymar Jr", "Vinícius Jr"),
            ("Michael Jordan", "LeBron James"),
            ("Fernando Alonso", "Carlos Sainz"),
            ("Cristiano Ronaldo", "Georgina Rodríguez"),
            ("alegría", "tristeza"),
            ("esperanza", "desesperación"),
            ("calma", "caos"),
            ("nostalgia", "recuerdo"),
            ("deseo", "miedo"),
            ("libertad", "soledad"),
            ("euforia", "melancolía"),
            ("sueño", "realidad"),
            ("ansiedad", "paz"),
            ("motivación", "rutina"),
            ("arte", "ciencia"),
            ("historia", "mito"),
            ("filosofía", "tecnología"),
            ("cultura", "identidad"),
            ("tiempo", "espacio"),
            ("realidad", "ficción"),
            ("creación", "destrucción"),
            ("costumbre", "tradición"),
            ("cultura", "tradición"),
            ("fantasía", "magia"),
        ]
        
        creadas = 0
        for buena, infiltrado in palabras:
            obj, created = PalabraPar.objects.get_or_create(
                palabra_buena=buena,
                palabra_infiltrado=infiltrado
            )
            if created:
                creadas += 1
                self.stdout.write(f'Creado: {buena} - {infiltrado}')
            else:
                self.stdout.write(f'Ya existe: {buena} - {infiltrado}')
        
        self.stdout.write(
            self.style.SUCCESS(f'Proceso completado. {creadas} nuevas palabras añadidas.')
        ) 